- name: Get UID for {{ user.username }}
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    kind: User
    name: "{{ user.username }}"
  register: user_object

- name: Add {{ user.username }} to CRW
  uri:
    url: '{{ keycloak_url }}/auth/admin/realms/codeready/users'
    validate_certs: false
    method: POST
    return_content: true
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ codeready_sso_admin_token.json.access_token }}"
    body:
      username: "{{ user.username }}"
      enabled: true
      emailVerified: true
      firstName: "{{ user.username }}"
      lastName: Developer
      email: "{{ user.username }}@no-reply.com"
      credentials:
        - type: password
          value: "{{ user.password }}"
          temporary: false
      federatedIdentities:
        - identityProvider: openshift-v4
          userId: "{{ user_object.resources[0].metadata.uid }}"
          userName: "{{ user.username }}"
    body_format: json
    status_code: 201,409
  register: user_creation