---
deploy_ocs: true
deploy_quay: true
deploy_service_mesh: true
deploy_gitea: true
deploy_sonarqube: true
deploy_nexus: true
deploy_3scale: true
deploy_crw: true
deploy_pipeline: true
deploy_workshop: true

pipeline_style: tekton
