---
- name: Validate that new Storage Class is available
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    kind: StorageClass
    name: '{{ new_default_storage_class }}'
  register: storageclass
  until: storageclass.resources|length > 0
  retries: 20
  delay: 30

- name: Change default StorageClass
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      - kind: StorageClass
        apiVersion: storage.k8s.io/v1
        metadata:
          name: gp2
          annotations:
            storageclass.kubernetes.io/is-default-class: 'false'
      - kind: StorageClass
        apiVersion: storage.k8s.io/v1
        metadata:
          name: '{{ new_default_storage_class }}'
          annotations:
            storageclass.kubernetes.io/is-default-class: 'true'
